title: Programming Languages
author:Jyoti Chaudhary
email:  jyotikrjc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A informative blog for knowing different Programming Languages

# social links
twitter_username: 
@JyotiCh55497157
github_username: jyoti22rjc
